# Generated by Django 5.2.5 on 2025-08-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitmovie',
            old_name='user',
            new_name='author',
        ),
    ]
